### PR TITLE
multiple-files

### PR DESCRIPTION
**Pull request by wiredolphin**
1. Re-arranged html structure, used html5 features.
2. Added multiple images capability, images can be added one-by-one or
selecting them with ctrl/cmd from the file dialog.
4. Output for multiple images can be represented by a single byte array
or with a byte array for each image, its identifier will be increased
with a trailing counter.
3. Added ‘GFXfontBitmap’ support.
4. Other smaller improvement.
NOTE: still under testing. Working example of this version can be found [here](https://wiredolphin.github.io/tools/image2cpp/index.html)

### CODE REVIEW

**Comment by javl** [comment]
Huge update, thanks.
I actually added multi-file support on a local branch, but seem to have messed up something so I'll just bin my version and add yours.

**Comment by wiredolphin** [comment]
Glad to hear that you've appreciated my work. Hope that also other user could take advantage of the new features of the tool, as it was useful to me when I discover it. I've seen other tools written for example in java, but in the thought that an on-line available tool can in certain situation be more handy, I'll work on trying to apply further improvements to your solution in the future.

**Comment by wiredolphin** [comment]
Sorry, found some critic errors that inhibits the byte array text input feature, on the current merged code. Will correct as soon as possible. Sorry.

**Comment by javl** [comment]
For me, this is mostly a testing feature. I don't expect it is used a lot; most work will be done img>byte instead of byte>img. I added (after the previous merge) a simple note to the page to ask anyone running into errors to open an issue, so we'll know when someone runs into trouble.

**Comment by wiredolphin** [comment]
I've just updated the code. It happened that the byte>img task was helpful to me, so I've preferred to keep it, thus correcting the bug. I'm just working on some other little improvements.

**Pull request merged**
